# Generated by Django 4.2 on 2024-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[("courier", "courier"), ("logistic", "logistic")],
                default="courier",
                editable=False,
                max_length=255,
            ),
        ),
    ]
